name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - branch-*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Analyze with SonarQube
        run: npx sonarqube-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=poc-ikea -Dsonar.projectKey=poc-ikea_pocapp3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
