name: cloudbuild

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  PROJECT_ID: clean-mason-391409
  SERVICE: pocapp3
  REGION: europe-west2
  SONAR_PROJECT_KEY: poc-ikea_pocapp2
  SONAR_ORGANIZATION: poc-ikea

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/1366473574/locations/global/workloadIdentityPools/githubactionspool/providers/github'
          service_account: 'terraform-sa@clean-mason-391409.iam.gserviceaccount.com'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: src
          args: >
           -Dsonar.organization=poc-ikea
           -Dsonar.projectKey=poc-ikea_pocapp3
        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} ./ --project ${{ env.PROJECT_ID }}
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/${{ env.PROJECT_ID }}/pocapp3
          service: pocapp3
          region: europe-west2
          platform: managed
          # Add any additional flags or configurations as needed
    env:
      PROJECT_ID: clean-mason-391409
